#!/bin/bash

# regression test  (need to run regrtest -ocaml in ../elsa before)
#
# run cfg on all ast files found
#

trap "echo Interupted; exit 1" SIGINT

# load variable ast-files
. ../asttools/regtest-ast-files

function usage(){
    echo "usage: regrtest [-skip <n>]"
    exit 1
}

skip=0
typeset -i count=0

while [ $# -ge 1 ] ; do
    case $1 in
	-skip)	
	    if [ $# -lt 2 ] ; then
		usage
	    fi
	    skip=$2
	    shift;;
	*)  usage;;
    esac
    shift
done

for f in $ast_files ; do
    if [ $skip -gt $count ]; then
	echo "[$count] skip $f"
    else
	echo "[$count] cfg $f"
	./cfg $f	
    fi
    count=$count+1
    rm -f output-count-ast output-count-ast-new 
done

