#!/usr/bin/perl -w
# -*-perl-*-
use strict;

# Chop out part of a file.

# Daniel S. Wilkerson dsw@cs.berkeley.edu

my $start = "---- START ----";  # NOTE: a filename can come after
my $stop  = "---- STOP ----\n";

while(<STDIN>) {
    last if /^${start}/;
}

while(<STDIN>) {
    last if $_ eq $stop;
    print;
}

while(<STDIN>) {
}
