ast_build.o: cc.ast.gen.h
astvisit.o: cc.ast.gen.h
astxml_lexer.o: astxml_tokens.h
astxml_lexer.o: astxml_lexer1_mid.gen.cc
astxml_lexer.o: astxml_lexer1_type.cc
astxml_lexer.yy.o: astxml_tokens.h
builtinops.o: cc.ast.gen.h
cc_ast_aux.o: cc.ast.gen.h
cc_elaborate.o: cc.ast.gen.h
cc_env.o: cc.ast.gen.h
cc.gr.gen.o: cc_tokens.h
cc.gr.gen.o: cc.ast.gen.h
cc_ocaml.o: cc.ast.gen.h
ccparse.o: cc.ast.gen.h
cc_print.o: cc.ast.gen.h
cc_scope.o: cc.ast.gen.h
cc_tcheck.o: cc.ast.gen.h
cc_tokens.o: cc_tokens.h
cc_type.o: cc.ast.gen.h
cc_type_xml.o: cc.ast.gen.h
cc_type_xml.o: astxml_tokens.h
cfg.o: cc.ast.gen.h
const_eval.o: cc.ast.gen.h
gnu.o: cc.ast.gen.h
implconv.o: cc.ast.gen.h
implint.o: cc.ast.gen.h
integrity.o: cc.ast.gen.h
kandr.o: cc.ast.gen.h
lexer.o: cc_tokens.h
lexer.yy.o: cc_tokens.h
main_astxmlparse.o: astxml_tokens.h
main_astxmlparse.o: cc.ast.gen.h
main_astxmlparse.o: astxml_parse1_0decl.gen.cc
main_astxmlparse.o: astxml_parse1_2ctrc.gen.cc
main_astxmlparse.o: astxml_parse1_3regc.gen.cc
main_astxmlparse.o: astxml_parse1_1defn.gen.cc
main.o: cc_tokens.h
main.o: cc.ast.gen.h
main.o: cc.gr.gen.h
mangle.o: cc.ast.gen.h
mtype.o: cc.ast.gen.h
notopt.o: cc.ast.gen.h
overload.o: cc.ast.gen.h
parssppt.o: cc_tokens.h
sprint.o: cc.ast.gen.h
stdconv.o: cc.ast.gen.h
template.o: cc.ast.gen.h
tlexer.o: cc_tokens.h
typelistiter.o: cc.ast.gen.h
variable.o: cc.ast.gen.h
xml.o: astxml_tokens.h
