#!/bin/sh
# make a tarball for distribution
      
# bail on error
set -e

# tarball dist name; e.g. elkhound-2002.08.12
distname=elsa-`date "+%Y.%m.%d"`
echo $distname

mkdir $distname || exit
cd $distname || exit

# main stuff
export CVSROOT=":ext:scott@manju.cs.berkeley.edu:/home/cvs-repository"
cvs export -D now smbase || exit
cvs export -D now ast || exit
cvs export -D now elkhound || exit
cvs export -D now elsa || exit

# toplevel files
cp elsa/toplevel/* .

# remove some files I don't want going into the external distribution
rm elsa/mkdist
rm -rf elsa/toplevel
rm elsa/test-parse-*

# package it up
cd ..
targz $distname || exit
rm -rf $distname

# test it
untargz ${distname}.tar.gz
cd ${distname}
./configure
make
make check

# blow away the test directory
if [ "$1" != "-keep" ]; then
  cd ..
  rm -rf $distname
fi







