#!/bin/sh
# parse a preprocessed file, and verify it
# can parse it and leave no ambiguities
               
if [ "$1" = "" ]; then
  echo "usage: $0 [-tr flag] file.i [file2.i [...]]"
  exit 0
fi

extra=""
if [ "$1" = "-tr" ]; then
  extra="-tr $2"
  shift
  shift
fi

while [ "$1" != "" ]; do
  fname="$1"
  shift

  echo "--------- $fname --------"
  
  case $fname in
    *.gz)
      inputFname=tmp.i
      echo "gunzip $fname >$inputFname"
      gunzip -c "$fname" >"$inputFname" || exit
      ;;

    *)
      inputFname="$fname"
      ;;
  esac

  # try to parse it
  echo "./ccparse $extra $inputFname"
  if ./ccparse -tr nohashline,permissive $extra "$inputFname"; then
    # ok
    true
  else
    code=$?
    echo "$fname: had errors"
    exit $code
  fi
done

exit 0



