#!/bin/sh
# test a perimeter binary

binary="./perimeter"
if [ "$1" != "" ]; then
  binary="$1"
fi

# all of perimeter's output is to stdout
echo "running: $binary >output"
if ! $binary >output; then
  echo "$binary failed directly"
  exit 2
fi

if ! grep -v "Time elapsed" <output | diff out.orig - >out.diff 2>&1  ; then
  # For some reason diff returns error code but an empty diff !
  if test -s out.diff; then
     echo "$binary got the wrong answer. See out.diff."
     exit 4
  fi
fi
echo "$binary seems to work"
rm -f out.diff
 