#!/bin/sh
# parse a preprocessed file, and verify it
# can parse it and leave no ambiguities
               
if [ "$1" = "" ]; then
  echo "usage: $0 file.i [file2.i [...]]"
  exit 0
fi

while [ "$1" != "" ]; do
  fname="$1"
  shift
  
  echo "--------- $fname --------"

  # see if the parser thinks it worked
  echo "cc/ccparse $fname"
  if cc/ccparse "$fname"; then
    # ok
    true
  else
    code=$?
    echo "$fname: had errors"
    exit $code
  fi

  # now print the AST and see if it's unambiguous
  echo "cc/ccparse -tr printTypedAST $fname"
  if cc/ccparse -tr printTypedAST "$fname" | grep ambiguous >/dev/null; then
    echo "$fname: had some ambiguities after typechecking"
    exit 4
  fi
done

exit 0



