#!/bin/sh
# build parsgen after configuring

(cd smbase ; make) || exit
(cd parsgen ; make) || exit
      
cat << EOF

Done building.

To parse some code, do:
  cd parsgen
  ./ccgr -tr parse-tree cc.gr some-file.c

(A simple example file is "c.in3".)

This will emit lots of stuff; grep for lines starting with
'(' to get the sexp parse trees.
EOF
