// cexp3.gr
// another go at C expressions, with user-supplied actions

terminals {
  // grab the lexer's token list
  include("cc.tok")
  
  // annotate some with semantic types
  token[int] L2_INT_LITERAL;
}

nonterm[int] Start -> e:Exp L2_EOF [ return e; ]

nonterm[int] Exp {
  -> i:L2_INT_LITERAL  [ return i; ]
  -> e1:Exp "+" e2:Exp [ return e1 + e2; ]
  -> e1:Exp "*" e2:Exp [ return e1 * e2; ]
}

