gramlex.yy.o: grampar.codes.h
grampar.o: gramast.ast.gen.h
grampar.o: grampar.tab.h
grampar.tab.o: gramast.ast.gen.h
cc/c.gr.gen.o: cc/c.ast.gen.h
cc/c_env.o: cc/c.ast.gen.h
cc/cc.gr.gen.o: cc/cc.ast.gen.h
cc/cc_ast_aux.o: cc/cc.ast.gen.h
cc/cc_env.o: cc/cc.ast.gen.h
cc/cc_print.o: cc/cc.ast.gen.h
cc/cc_scope.o: cc/cc.ast.gen.h
cc/cc_tcheck.o: cc/cc.ast.gen.h
cc/ccgrmain.o: cc/c.ast.gen.h
cc/ccgrmain.o: cc/c.gr.gen.h
cc/ccparse.o: cc/cc.ast.gen.h
cc/cparse.o: cc/c.ast.gen.h
cc/exprequal.o: cc/c.ast.gen.h
cc/exprvisit.o: cc/c.ast.gen.h
cc/main.o: cc/cc.ast.gen.h
cc/main.o: cc/cc.gr.gen.h
cc/paths.o: cc/c.ast.gen.h
cc/postorder.o: cc/c.ast.gen.h
cc/stubs.o: cc/c.ast.gen.h
cc/tcheck.o: cc/c.ast.gen.h
cc2/cc2main.o: cc2/cc2.gr.gen.h
