// gramlex.h
// GrammarLexer: a c++ lexer class for use with Flex's generated c++ scanner

#ifndef __GRAMLEX_H
#define __GRAMLEX_H


// This included file is part of the Flex distribution.  It is
// installed in /usr/include on my Linux machine.  By including it, we
// get the declaration of the yyFlexLexer class.  Note that the file
// that flex generates, gramlex.yy.cc, also #includes this file.
// Perhaps also worth mentioning: I'm developing this with flex 2.5.4.
#include <FlexLexer.h>


// may as well pull in the token constant definitions (generated by
// Bison from grammar.y) to interpret return value of yylex()
#include "grampar.tab.h"

// a couple more tokens                            
#define TOK_EOF 0             // better name
#define TOK_INCLUDE 1         // not seen by parser


// other includes
#include "str.h"              // string
#include "objlist.h"          // ObjList
#include "fileloc.h"          // SourceLocation


// this class just holds the lexer state so it is properly encapsulated
// (and therefore, among other things, re-entrant)
class GrammarLexer : public yyFlexLexer {
public:      // types
  enum Constants {
    lexBufferSize = 4096,          // size of new lex buffers
  };

private:     // data
  // state of a file we were or are lexing
  struct FileState : public SourceLocation {
    istream *source;               // (owner?) source stream
    yy_buffer_state *bufstate;     // (owner?) flex's internal buffer state

  public:
    FileState(SourceFile *file, istream *source);
    ~FileState();

    FileState(FileState const &obj);
    FileState& operator= (FileState const &obj);
  };

  FileState fileState;             // state for file we're lexing now
  ObjList<FileState> fileStack;    // stack of files we will return to

public:      // data
  int commentStartLine;            // for reporting unterminated C comments
  int integerLiteral;              // to store number literal value
  string stringLiteral;            // string in quotes, minus the quotes
  string includeFileName;          // name in an #include directive

  // defined in the base class, FlexLexer:
  //   const char *YYText();           // start of matched text
  //   int YYLeng();                   // number of matched characters

private:     // funcs                      
  // called when a newline is encountered
  void newLine() { fileState.newLine(); }

public:      // funcs
  // create a new lexer that will read from to named stream,
  // or stdin if it is NULL
  GrammarLexer(char const *fname = "<stdin>",
               istream * /*owner*/ source = NULL);

  // clean up
  ~GrammarLexer();

  // get current token as a string
  string curToken() const;
  int curLen() const { return const_cast<GrammarLexer*>(this)->YYLeng(); }

  // read the next token and return its code; returns TOK_EOF for end of file;
  // this function is defined in flex's output source code; this one
  // *does* return TOK_INCLUDE
  virtual int yylex();

  // similar to yylex, but process TOK_INCLUDE internally
  int yylexInc();

  // info about location of current token
  char const *curFname() const { return fileState.fname(); }
  int curLine() const { return fileState.line; }
  int curCol() const;
  SourceLocation const &curLoc() const { return fileState; }
  string curLocStr() const;    // string with file/line/col

  // error reporting; called by the lexer code
  void err(char const *msg);          // msg should not include a newline
  void errorUnterminatedComment();
  void errorMalformedInclude();
  void errorIllegalCharacter(char ch);

  // for processing includes
  void recursivelyProcess(char const *fname, istream * /*owner*/ source);
  void popRecursiveFile();
  bool hasPendingFiles() const;
};


#endif // __GRAMLEX_H
