#!/bin/sh
# run Simplify with no axioms

here=`dirname $0`

# empty.ax should exist in $here and be empty
if [ ! -f "$here/empty.ax" ]; then
  touch "$here/empty.ax" || exit
fi
export AXIOMDIR="$here"

exec /usr/local/escjava/bin/Simplify -ax empty "$@"
#exec $HOME/bld/escjava/bin/Simplify -ax empty "$@"

